accounts/urls.py
from django.urls import path, include

from .views import register, login, logout, profile, edit_profile


app_name = "accounts"

urlpatterns = [
    path("register/", register, name="register"),
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
    path("profile/", profile, name="profile"),
    path("edit-profile/", edit_profile, name="edit_profile"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard.views import index


urlpatterns = [
    path("", index, name="index"),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("ideas/", include("ideas.urls", namespace="ideas")),
    path("investments/", include("investments.urls", namespace="investments")),
    path("admin/", admin.site.urls),
]

ideas/urls.py
from django.urls import path, include

from .views import idea, create_idea, delete_idea, edit_idea


app_name = "ideas"

urlpatterns = [
    path("<int:idea_id>/", idea, name="idea"),
    path("create_idea/", create_idea, name="create_idea"),
    path("<int:idea_id>/edit/", edit_idea, name="edit_idea"),
    path("<int:idea_id>/delete/", delete_idea, name="delete_idea"),
]

investments/urls.py
from django.urls import path
from .views import make_investment, invested, accept_investment

app_name = 'investments'

urlpatterns = [
    path('make_investment/<int:idea_id>/', make_investment, name='make_investment'),
    path('invested/', invested, name='invested'),
    path('accept_investment/<int:investment_id>/', accept_investment, name='accept_investment'),
]

ideas/models.py
from django.db import models
from accounts.models import UserProfile


class Idea(models.Model):
    user_profile = models.ForeignKey(
        UserProfile, on_delete=models.CASCADE, related_name="ideas"
    )
    title = models.CharField(max_length=200)
    investment_value = models.DecimalField(max_digits=10, decimal_places=2)
    elapsed_time = models.IntegerField(default=0)
    return_on_investment = models.DecimalField(max_digits=5, decimal_places=2)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

ideas/forms.py
from django import forms
from .models import Idea


class IdeaForm(forms.ModelForm):
    class Meta:
        model = Idea
        fields = [
            "title",
            "investment_value",
            "elapsed_time",
            "return_on_investment",
            "description",
        ]

ideas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import (
    IdeaForm,
)
from .models import UserProfile

from ideas.models import Idea

from django.core.exceptions import PermissionDenied


from django.forms import inlineformset_factory


@login_required
def idea(request, idea_id):
    idea = get_object_or_404(Idea, pk=idea_id)

    any_accepted_investment = idea.investments.filter(status="aprovado").exists()

    return render(request, "ideas/idea.html", {
        "idea": idea,
        "any_accepted_investment": any_accepted_investment
    })


@login_required
def create_idea(request):
    if request.method == "POST":
        form = IdeaForm(request.POST)
        if form.is_valid():
            idea = form.save(commit=False)
            idea.user_profile = request.user.user_profile
            idea.save()
            return redirect("ideas:idea", idea_id=idea.id)
    else:
        form = IdeaForm()
    return render(request, "ideas/create_idea.html", {"form": form})


@login_required
def edit_idea(request, idea_id):
    idea = get_object_or_404(Idea, pk=idea_id)
    if idea.user_profile.user != request.user:
        raise PermissionDenied()

    if request.method == "POST":
        form = IdeaForm(request.POST, instance=idea)
        if form.is_valid():
            form.save()
            return redirect("ideas:idea", idea_id=idea.id)
    else:
        form = IdeaForm(instance=idea)
    return render(request, "ideas/edit_idea.html", {"form": form, "idea": idea})


@login_required
def delete_idea(request, idea_id):
    idea = get_object_or_404(Idea, pk=idea_id)
    if idea.user_profile.user != request.user:
        raise PermissionDenied()
    idea.delete()
    return redirect("dashboard:browse")

ideas/templates/ideas/card_idea.html
{% block content %}

<div class="col-md-4 mb-4">
    <div class="card h-100">
        <div class="card-body">
            <h5 class="card-title">{{ idea.title }}</h5>
            <p class="card-text">{{ idea.description|truncatewords:20 }}</p>
            <a href="{% url 'ideas:idea' idea.id %}" class="btn btn-primary p-2 d-inline-block">Saiba Mais</a>
            {% if idea.user_profile.entrepreneur_tier == 'premium' %}
                <p class="card border border-warning bg-warning p-2 d-inline-block">Premium</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

ideas/templates/ideas/create_idea.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block title %}Criar Ideia{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h2>Criar Nova Ideia</h2>
                </div>
                <div class="card-body">
                    <form method="post" action="{% url 'accounts:profile' %}">
                        {% csrf_token %}
                        <div class="form-group mb-4">
                            {{ form.title.errors }}
                            <label for="id_title">Título da Ideia</label>
                            {{ form.title }}
                        </div>
                        <div class="form-group mb-4">
                            {{ form.description.errors }}
                            <label for="id_description" class="font-weight-bold">Descrição</label>
                            <div>{{ form.description }}</div>
                        </div>
                        <div class="form-group mb-4">
                            <label for="id_investment_value">Valor Investido: R$</label>
                            {{ form.investment_value }} Reais
                        </div>
                        <div class="form-group mb-5">
                            {{ form.elapsed_time.errors }}
                            <label for="id_elapsed_time">Tempo de Retorno (meses)</label>
                            {{ form.elapsed_time }}
                        </div>
                        <div class="form-group mb-5">
                            {{ form.return_on_investment.errors }}
                            <label for="id_return_on_investment">Retorno de Capital (%)</label>
                            {{ form.return_on_investment }}
                        </div>
                        <div class="form-group mb-4">
                            <button type="submit" class="btn btn-primary">Criar Ideia</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ideas/templates/ideas/edit_idea.html
{% extends "dashboard/base.html" %}

{% block title %}Editar Ideia{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h2 class="mb-0">Editar Ideia</h2>
                </div>
                <div class="card-body">
                    <form id="form-edit" method="post">
                        {% csrf_token %}
                        <div class="form-group mb-4">
                            <label for="id_title" class="font-weight-bold">Título da Ideia</label>
                            {{ form.title }}
                        </div>
                        <div class="form-group mb-4">
                            <label for="id_description" class="font-weight-bold">Descrição</label>
                            <div>{{ form.description }}</div>
                        </div>
                        <div class="form-group mb-4">
                            <label for="id_investment_value" class="font-weight-bold">Valor Investido: R$</label>
                            {{ form.investment_value }} Reais
                        </div>
                        <div class="form-group mb-4">
                            <label for="id_elapsed_time" class="font-weight-bold">Tempo de Retorno (meses)</label>
                            {{ form.elapsed_time }}
                        </div>
                        <div class="form-group mb-4">
                            <label for="id_return_on_investment" class="font-weight-bold">Retorno de Capital (%)</label>
                            {{ form.return_on_investment }}
                        </div>
                    </form>
                    <form id="form-delete" style="display: none;" method="post" action="{% url 'ideas:delete_idea' idea.id %}">
                        {% csrf_token %}
                    </form>
                    <div class="form-group mb-4">
                        <button style="float: left;" onclick="document.getElementById('form-delete').submit()" class="btn btn-danger">Apagar Ideia</button>
                        <button style="float: right;" onclick="document.getElementById('form-edit').submit()" class="btn btn-primary">Salvar Alterações</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ideas/templates/ideas/idea.html
{% extends "dashboard/base.html" %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-8">
            <div class="card {% if idea.user_profile.entrepreneur_tier == 'premium' %}bg-warning{% endif %}">
                <div class="card-header">
                    <h1>{{ idea.title }}</h1>
                </div>
                <div class="card-body">
                    <h5 class="card-title">Detalhes da Ideia</h5>
                    <p class="card-text"><strong>Empreendedor:</strong> {{ idea.user_profile.user.first_name }} {{ idea.user_profile.user.last_name }}</p>
                    <p class="card-text"><strong>Contato:</strong> {{ idea.user_profile.user.email }}</p>
                    <p class="card-text"><strong>Descrição:</strong> {{ idea.description }}</p>
                    <p class="card-text"><strong>Valor investido: R$</strong> {{ idea.investment_value }}</p>
                    <p class="card-text"><strong>Tempo de retorno:</strong> {{ idea.elapsed_time }} meses</p>
                    <p class="card-text"><strong>Retorno de capital:</strong> {{ idea.return_on_investment }}%</p>
                    <div class="d-flex justify-content-between mt-4">
                        <button onclick="history.back()" class="btn btn-secondary">Voltar</button>
                        {% if idea.user_profile.user == request.user %}
                            <a href="{% url 'ideas:edit_idea' idea.id %}" class="btn btn-warning">Editar Ideia</a>
                        {% endif %}
                        {% if user.userprofile.role == 'investor' and not any_accepted_investment %}
                            <a href="{% url 'investments:make_investment' idea.id %}" class="btn btn-primary">Aplicar</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h2>Propostas</h2>
                </div>
                <div class="card-body">
                    <ul class="row">
                        {% for investment in idea.investments.all %}
                            <div class="col-12 mb-4">
                                {% include 'investments/card_investment.html' with investment=investment %}
                            </div>
                        {% empty %}
                            <div class="col-12">
                                <p>Nenhuma proposta foi feita ainda.</p>
                            </div>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}