core/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard.views import index


urlpatterns = [
    path("", index, name="index"),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("ideas/", include("ideas.urls", namespace="ideas")),
    path("investments/", include("investments.urls", namespace="investments")),
    path("admin/", admin.site.urls),
]

investments/urls.py
from django.urls import path
from .views import make_investment, invested, accept_investment

app_name = 'investments'

urlpatterns = [
    path('make_investment/<int:idea_id>/', make_investment, name='make_investment'),
    path('invested/', invested, name='invested'),
    path('accept_investment/<int:investment_id>/', accept_investment, name='accept_investment'),
]

investments/models.py
from django.db import models
from django.contrib.auth.models import User
from decimal import Decimal
from django.core.validators import MinValueValidator

from ideas.models import Idea

from accounts.models import UserProfile

class Investment(models.Model):
    investor = models.ForeignKey(
        UserProfile, on_delete=models.CASCADE, related_name="investments"
    )

    STATUS_CHOICES = [
        ('aprovada', 'Aprovada'),
        ('pendente', 'Pendente'),
        ('rejeitada', 'Rejeitada'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pendente')
    idea = models.ForeignKey(Idea, on_delete=models.CASCADE, related_name="investments", null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    date_invested = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.investor.username} invested {self.amount} in {self.idea.title}"

investments/forms.py
from django import forms
from .models import Investment


class InvestmentForm(forms.ModelForm):
    class Meta:
        model = Investment
        fields = [
            "amount",
        ]

investments/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import InvestmentForm
from ideas.models import Idea
from .models import Investment
from django.contrib.auth.decorators import login_required

from django.contrib import messages

@login_required
def make_investment(request, idea_id):
    idea = get_object_or_404(Idea, id=idea_id)
    
    if request.method == 'POST':
        form = InvestmentForm(request.POST)
        if form.is_valid():
            investment = form.save(commit=False)
            investment.investor = request.user.userprofile
            investment.idea = idea
            investment.save()
            messages.success(request, 'Investimento realizado com sucesso!')
            return redirect("ideas:idea", idea_id=idea_id)
    else:
        form = InvestmentForm(initial={'idea': idea})
    
    return render(request, 'investments/make_investment.html', {'form': form, 'idea': idea})


@login_required
def invested(request):
    return render(request, 'investments/invested.html')


@login_required
def accept_investment(request, investment_id):
    investment = get_object_or_404(Investment, id=investment_id)
    idea = investment.idea

    investment.status = 'aprovado'
    investment.save()

    Investment.objects.filter(idea=idea).exclude(id=investment_id).update(status='rejeitado')

    any_accepted_investment = idea.investments.filter(status='aprovado').exists()

    return render(request, 'ideas/idea.html', {
        'idea': idea,
        'any_accepted_investment': any_accepted_investment,
    })

investments/templates/investments/card_investment.html
{% block content %}

<div class="col-12 mb-4">
    <div class="card h-100">
        <div class="card-body">
            <h5 class="card-title">Ideia: {{ investment.idea.title }}</h5>
            <h5 class="card-title">Investidor: {{ investment.investor.user.first_name }} {{ investment.investor.user.last_name }}</h5>
            <p class="card-text">Valor: R${{ investment.amount }}</p>
            <div class="card mt-3 px-3 py-1 text-white {% if investment.status == 'aprovado' %}bg-success{% elif investment.status == 'pendente' %}bg-warning{% elif investment.status == 'rejeitado' %}bg-danger{% else %}bg-secondary{% endif %}">
                {{ investment.status|capfirst }}
            </div>
            {% if not any_accepted_investment and investment.status != 'aprovado' and investment.idea.user_profile.user == request.user %}
                <a href="{% url 'investments:accept_investment' investment.id %}" class="btn btn-primary mt-3">Aceitar</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

investments/templates/investments/invested.html
{% extends 'dashboard/base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Você aplicou</h2>
</div>
{% endblock %}

investments/templates/investments/make_investment.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block title %}Investir em uma Ideia{% endblock %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Investment</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container">
        <h2>Investir na ideia:</h2>
        <h3>{{ idea.title }}</h3>
        <form method="post" action="{% url 'investments:make_investment' idea.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Invest</button>
        </form>
    </div>
</body>
{% endblock %}